### ISSUE TITLE
Translation to Spanish for version 1.18.2 :)

### ISSUE THREAD

**Issue by 121415A** [team-abnormals/clayworks#14]
{
"block.clayworks.black_terracotta_brick_slab": "Losa de Ladrillo de Terracota Negra",
"block.clayworks.black_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Negra",
"block.clayworks.black_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Negra",
"block.clayworks.black_terracotta_brick_wall": "Muro de Ladrillo de Terracota Negra",
"block.clayworks.black_terracotta_bricks": "Ladrillos de Terracota Negra",
"block.clayworks.black_terracotta_slab": "Losa de Terracota Negra",
"block.clayworks.black_terracotta_stairs": "Escaleras de Terracota Negra",
"block.clayworks.black_terracotta_vertical_slab": "Losa Vertical de Terracota Negra",
"block.clayworks.black_terracotta_wall": "Muro de Terracota Negra",
"block.clayworks.blue_terracotta_brick_slab": "Losas de Ladrillo de Terracota Azul",
"block.clayworks.blue_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Azul",
"block.clayworks.blue_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Azul",
"block.clayworks.blue_terracotta_brick_wall": "Muro de Ladrillo de Terracota Azul",
"block.clayworks.blue_terracotta_bricks": "Ladrillos de Terracota Azul",
"block.clayworks.blue_terracotta_slab": "Losas de Terracota Azul",
"block.clayworks.blue_terracotta_stairs": "Escaleras de Terracota Azul",
"block.clayworks.blue_terracotta_vertical_slab": "Losa Vertical de Terracota Azul",
"block.clayworks.blue_terracotta_wall": "Muro de Terracota Azul",
"block.clayworks.brown_terracotta_brick_slab": "Losas de Ladrillo de Terracota Marrón",
"block.clayworks.brown_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Marrón",
"block.clayworks.brown_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Marrón",
"block.clayworks.brown_terracotta_brick_wall": "Muro de Ladrillo de Terracota Marrón",
"block.clayworks.brown_terracotta_bricks": "Ladrillos de Terracota Marrón",
"block.clayworks.brown_terracotta_slab": "Losas de Terracota Marrón",
"block.clayworks.brown_terracotta_stairs": "Escaleras de Ladrillo de Terracota Marrón",
"block.clayworks.brown_terracotta_vertical_slab": "Losa Vertical de Ladrillo de Terracota Marrón",
"block.clayworks.brown_terracotta_wall": "Muro de Ladrillo de Terracota Marrón",
"block.clayworks.chiseled_black_terracotta_bricks": "Ladrillos de Terracota Negra Labrados",
"block.clayworks.chiseled_blue_terracotta_bricks": "Ladrillos de Terracota Azul Labrados",
"block.clayworks.chiseled_bricks": "Ladrillos Labrados",
"block.clayworks.chiseled_brown_terracotta_bricks": "Ladrillos de Terracota Marrón Labrados",
"block.clayworks.chiseled_cyan_terracotta_bricks": "Ladrillos de Terracota Cian Labrados",
"block.clayworks.chiseled_gray_terracotta_bricks": "Ladrillos de Terracota Gris Labrados",
"block.clayworks.chiseled_green_terracotta_bricks": "Ladrillos de Terracota Verde Labrados",
"block.clayworks.chiseled_light_blue_terracotta_bricks": "Ladrillos de Terracota Azul Claro Labrados",
"block.clayworks.chiseled_light_gray_terracotta_bricks": "Ladrillos de Terracota Gris Claro Labrados",
"block.clayworks.chiseled_lime_terracotta_bricks": "Ladrillos de Terracota Lima Labrados",
"block.clayworks.chiseled_magenta_terracotta_bricks": "Ladrillos de Terracota Magenta Labrados",
"block.clayworks.chiseled_orange_terracotta_bricks": "Ladrillos de Terracota Naranja Labrados",
"block.clayworks.chiseled_pink_terracotta_bricks": "Ladrillos de Terracota Rosa Labrados",
"block.clayworks.chiseled_purple_terracotta_bricks": "Ladrillos de Terracota Morada Labrados",
"block.clayworks.chiseled_red_terracotta_bricks": "Ladrillos de Terracota Roja Labrados",
"block.clayworks.chiseled_terracotta_bricks": "Ladrillos de Terracota Labrados",
"block.clayworks.chiseled_white_terracotta_bricks": "Ladrillos de Terracota Blancos Labrados",
"block.clayworks.chiseled_yellow_terracotta_bricks": "Ladrillos de Terracota Amarillos Labrados",
"block.clayworks.cyan_terracotta_brick_slab": "Losa de Ladrillo de Terracota Cian",
"block.clayworks.cyan_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Cian",
"block.clayworks.cyan_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Cian",
"block.clayworks.cyan_terracotta_brick_wall": "Muro de Ladrillo de Terracota Cian",
"block.clayworks.cyan_terracotta_bricks": "Ladrillos de Terracota Cian",
"block.clayworks.cyan_terracotta_slab": "Losa de Terracota Cian",
"block.clayworks.cyan_terracotta_stairs": "Escaleras de Terracota Cian",
"block.clayworks.cyan_terracotta_vertical_slab": "Losa Vertical de Terracota Cian",
"block.clayworks.cyan_terracotta_wall": "Muro de Terracota Cian",
"block.clayworks.gray_terracotta_brick_slab": "Losa de Ladrillo de Terracota Gris",
"block.clayworks.gray_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Gris",
"block.clayworks.gray_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Gris",
"block.clayworks.gray_terracotta_brick_wall": "Muro de Ladrillo de Terracota Gris",
"block.clayworks.gray_terracotta_bricks": "Ladrillos de Terracota Gris",
"block.clayworks.gray_terracotta_slab": "Losa de Terracota Gris",
"block.clayworks.gray_terracotta_stairs": "Escaleras de Terracota Gris",
"block.clayworks.gray_terracotta_vertical_slab": "Losa Vertical de Terracota Gris",
"block.clayworks.gray_terracotta_wall": "Muro de Terracota Gris",
"block.clayworks.green_terracotta_brick_slab": "Losa de Ladrillo de Terracota Verde",
"block.clayworks.green_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Verde",
"block.clayworks.green_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Verde",
"block.clayworks.green_terracotta_brick_wall": "Muro de Ladrillo de Terracota Verde",
"block.clayworks.green_terracotta_bricks": "Ladrillos de Terracota Verde",
"block.clayworks.green_terracotta_slab": "Losa de Terracota Verde",
"block.clayworks.green_terracotta_stairs": "Escaleras de Terracota Verde",
"block.clayworks.green_terracotta_vertical_slab": "Losa Vertical de Terracota Verde",
"block.clayworks.green_terracotta_wall": "Muro de Terracota Verde",
"block.clayworks.kiln": "Horno de Cerámica",
"block.clayworks.light_blue_terracotta_brick_slab": "Losa de Ladrillo de Terracota Azul Claro",
"block.clayworks.light_blue_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Azul Claro",
"block.clayworks.light_blue_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Azul Claro",
"block.clayworks.light_blue_terracotta_brick_wall": "Muro de Ladrillo de Terracota Azul Claro",
"block.clayworks.light_blue_terracotta_bricks": "Ladrillos de Terracota Azul Claro",
"block.clayworks.light_blue_terracotta_slab": "Losa de Terracota Azul Claro",
"block.clayworks.light_blue_terracotta_stairs": "Escaleras de Terracota Azul Claro",
"block.clayworks.light_blue_terracotta_vertical_slab": "Losa Vertical de Terracota Azul Claro",
"block.clayworks.light_blue_terracotta_wall": "Muro de Terracota Azul Claro",
"block.clayworks.light_gray_terracotta_brick_slab": "Losa de Ladrillo de Terracota Gris Claro",
"block.clayworks.light_gray_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Gris Claro",
"block.clayworks.light_gray_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Gris Claro",
"block.clayworks.light_gray_terracotta_brick_wall": "Muro de Ladrillo de Terracota Gris Claro",
"block.clayworks.light_gray_terracotta_bricks": "Ladrillos de Terracota Gris Claro",
"block.clayworks.light_gray_terracotta_slab": "Losa de Terracota Gris Claro",
"block.clayworks.light_gray_terracotta_stairs": "Escaleras de Terracota Gris Claro",
"block.clayworks.light_gray_terracotta_vertical_slab": "Losa Vertical de Terracota Gris Claro",
"block.clayworks.light_gray_terracotta_wall": "Muro de Terracota Gris Claro",
"block.clayworks.lime_terracotta_brick_slab": "Losa de Ladrillo de Terracota Lima",
"block.clayworks.lime_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Lima",
"block.clayworks.lime_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Lima",
"block.clayworks.lime_terracotta_brick_wall": "Muro de Ladrillo de Terracota Lima",
"block.clayworks.lime_terracotta_bricks": "Ladrillos de Terracota Lima",
"block.clayworks.lime_terracotta_slab": "Losa de Terracota Lima",
"block.clayworks.lime_terracotta_stairs": "Escaleras de Terracota Lima",
"block.clayworks.lime_terracotta_vertical_slab": "Losa Vertical de Terracota Lima",
"block.clayworks.lime_terracotta_wall": "Muro de Terracota Lima",
"block.clayworks.magenta_terracotta_brick_slab": "Losa de Ladrillo de Terracota Magenta",
"block.clayworks.magenta_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Magenta",
"block.clayworks.magenta_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Magenta",
"block.clayworks.magenta_terracotta_brick_wall": "Muro de Ladrillo de Terracota Magenta",
"block.clayworks.magenta_terracotta_bricks": "Ladrillos de Terracota Magenta",
"block.clayworks.magenta_terracotta_slab": "Losa de Terracota Magenta",
"block.clayworks.magenta_terracotta_stairs": "Escaleras de Terracota Magenta",
"block.clayworks.magenta_terracotta_vertical_slab": "Losa Vertical de Terracota Magenta",
"block.clayworks.magenta_terracotta_wall": "Muro de Terracota Magenta",
"block.clayworks.orange_terracotta_brick_slab": "Losa de Ladrillo de Terracota Naranja",
"block.clayworks.orange_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Naranja",
"block.clayworks.orange_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Naranja",
"block.clayworks.orange_terracotta_brick_wall": "Muro de Ladrillo de Terracota Naranja",
"block.clayworks.orange_terracotta_bricks": "Ladrillos de Terracota Naranja",
"block.clayworks.orange_terracotta_slab": "Losa de Terracota Naranja",
"block.clayworks.orange_terracotta_stairs": "Escaleras de Terracota Naranja",
"block.clayworks.orange_terracotta_vertical_slab": "Losa Vertical de Terracota Naranja",
"block.clayworks.orange_terracotta_wall": "Muro de Terracota Naranja",
"block.clayworks.pink_terracotta_brick_slab": "Losa de Ladrillo de Terracota Rosa",
"block.clayworks.pink_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Rosa",
"block.clayworks.pink_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Rosa",
"block.clayworks.pink_terracotta_brick_wall": "Muro de Ladrillo de Terracota Rosa",
"block.clayworks.pink_terracotta_bricks": "Ladrillos de Terracota Rosa",
"block.clayworks.pink_terracotta_slab": "Losa de Terracota Rosa",
"block.clayworks.pink_terracotta_stairs": "Escaleras de Terracota Rosa",
"block.clayworks.pink_terracotta_vertical_slab": "Losa Vertical de Terracota Rosa",
"block.clayworks.pink_terracotta_wall": "Muro de Terracota Rosa",
"block.clayworks.purple_terracotta_brick_slab": "Losa de Ladrillo de Terracota Morada",
"block.clayworks.purple_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Morada",
"block.clayworks.purple_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Morada",
"block.clayworks.purple_terracotta_brick_wall": "Muro de Ladrillo de Terracota Morada",
"block.clayworks.purple_terracotta_bricks": "Ladrillos de Terracota Morada",
"block.clayworks.purple_terracotta_slab": "Losa de Terracota Morada",
"block.clayworks.purple_terracotta_stairs": "Escaleras de Terracota Morada",
"block.clayworks.purple_terracotta_vertical_slab": "Losa Vertical de Terracota Morada",
"block.clayworks.purple_terracotta_wall": "Muro de Terracota Morada",
"block.clayworks.red_terracotta_brick_slab": "Losa de Ladrillo de Terracota Roja",
"block.clayworks.red_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Roja",
"block.clayworks.red_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Roja",
"block.clayworks.red_terracotta_brick_wall": "Muro de Ladrillo de Terracota Roja",
"block.clayworks.red_terracotta_bricks": "Ladrillos de Terracota Roja",
"block.clayworks.red_terracotta_slab": "Losa de Terracota Roja",
"block.clayworks.red_terracotta_stairs": "Escaleras de Terracota Roja",
"block.clayworks.red_terracotta_vertical_slab": "Losa Vertical de Terracota Roja",
"block.clayworks.red_terracotta_wall": "Muro de Terracota Roja",
"block.clayworks.terracotta_brick_slab": "Losa de Ladrillo de Terracota",
"block.clayworks.terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota",
"block.clayworks.terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota",
"block.clayworks.terracotta_brick_wall": "Muro de Ladrillo de Terracota",
"block.clayworks.terracotta_bricks": "Ladrillos de Terracota",
"block.clayworks.terracotta_slab": "Losa de Terracota",
"block.clayworks.terracotta_stairs": "Escaleras de Terracota",
"block.clayworks.terracotta_vertical_slab": "Losa Vertical de Terracota",
"block.clayworks.terracotta_wall": "Muro de Terracota",
"block.clayworks.white_terracotta_brick_slab": "Losa de Ladrillo de Terracota Blanca",
"block.clayworks.white_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Blanca",
"block.clayworks.white_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Blanca",
"block.clayworks.white_terracotta_brick_wall": "Muro de Ladrillo de Terracota Blanca",
"block.clayworks.white_terracotta_bricks": "Ladrillos de Terracota Blanca",
"block.clayworks.white_terracotta_slab": "Losa de Terracota Blanca",
"block.clayworks.white_terracotta_stairs": "Escaleras de Terracota Blanca",
"block.clayworks.white_terracotta_vertical_slab": "Losa Vertical de Terracota Blanca",
"block.clayworks.white_terracotta_wall": "Muro de Terracota Blanca",
"block.clayworks.yellow_terracotta_brick_slab": "Losa de Ladrillo de Terracota Amarilla",
"block.clayworks.yellow_terracotta_brick_stairs": "Escaleras de Ladrillo de Terracota Amarilla",
"block.clayworks.yellow_terracotta_brick_vertical_slab": "Losa Vertical de Ladrillo de Terracota Amarilla",
"block.clayworks.yellow_terracotta_brick_wall": "Muro de Ladrillo de Terracota Amarilla",
"block.clayworks.yellow_terracotta_bricks": "Ladrillos de Terracota Amarilla",
"block.clayworks.yellow_terracotta_slab": "Losa de Terracota Amarilla",
"block.clayworks.yellow_terracotta_stairs": "Escaleras de Terracota Amarilla",
"block.clayworks.yellow_terracotta_vertical_slab": "Losa Vertical de Terracota Amarilla",
"block.clayworks.yellow_terracotta_wall": "Muro de Terracota Amarilla",
"container.clayworks.kiln": "Horno de Cerámica",
"gui.clayworks.category.baking": "Horneado",
"subtitles.clayworks.block.kiln.smoke": "Humo del Horno de Cerámica"
}

**Comment by bageldotjpg** [comment]
1.18.2 is unfortunately no longer supported. Feel free to open a pull request for a more recent version, though.
