### ISSUE TITLE
Resource and data packs cannot edit clayworks blocks or items

### ISSUE THREAD

**Issue by pskfyi** [team-abnormals/clayworks#26]
On v3.0.1 / Forge  / minecraft 1.20.1, resource packs cannot change the names of this mod's blocks or items, and data packs cannot edit the default recipes. KubeJS can be used as a workaround.

**Comment by bageldotjpg** [comment]
Yes they can, there's literally no way they couldn't
Check your syntax and make sure your data & resource packs are loading above Clayworks

**Comment by pskfyi** [comment]
> make sure your data & resource packs are loading above Clayworks

Thank you, I had no idea that ordering could be an issue and this was indeed the cause.
