### ISSUE TITLE
Kilns Do Not Emit Sounds [Forge, v2.0.1 for v1.19.2]

### ISSUE THREAD

**Issue by sdarkwell** [team-abnormals/clayworks#7]
**Hello!**

Firstly, thank you for your excellent mod! :)

Unlike furnaces, blast furnaces, and smokers, Clayworks' kilns do not emit any sounds while smelting.

This issue affects Clayworks v2.0.1 for Minecraft v1.19.2 and Force v43.2.4.

Hope this issue report helps.

**Thank you and be well!**
\- S.

**Comment by bageldotjpg** [comment]
Fixed in 99c180511c7af630e08e8140fa350bbf1178ad58
